### ISSUE TITLE
上线后无提醒

### ISSUE THREAD

**Issue by xiaobei97** [kingz40o/Aggressor_dingding#1]
大佬您好，在使用这款脚本过程中，已经替换脚本中第一行的dt_token的实际值，保存后load到脚本管理器中，经测试有机器上线后在钉钉群里机器人没有消息提醒，请问是哪里的问题呢？（使用CS4.1）

**Comment by kingz40o** [comment]
不要load到脚本管理器
在本机或者服务器运行，服务器运行可长期监听通知。 ` ./agscript cs服务端IP 端口 任意用户名 cs密码 dingding.cna`
比如在cs服务器里：./agscript 127.0.0.1 63790 admin password dingding.cna
